
USE MAS

INSERT	INTO Lecturer(Email,Name, Phone, MeetingURL, Status, Gender, Birthday, Address, AvatarURL)
VALUES	('khiemtd@fe.edu.vn',N'Trần Duy Khiêm',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('linhnh@fe.edu.vn',N'Nguyễn Hoàng Linh',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('linhvt@fe.edu.vn',N'Vũ Tùng Linh',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('duongttt@fe.edu.vn',N'Tô Thị Thùy Dương',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('lanln@fe.edu.vn',N'Lưu Nhật Lan',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('mailtn@fe.edu.vn',N'Lê thị Ngọc Mai',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('thanhđt@fe.edu.vn',N'Đinh Tiến Thành',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('tultc@fe.edu.vn',N'La Thị Cẩm Tú',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('camđth@fe.edu.vn',N'Đỗ thị Hồng cẩm',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('kieuta@fe.edu.vn',N'Trần Anh Kiều',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('đoanđc@fe.edu.vn',N'Đặng Công Đoàn',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('tuendm@fe.edu.vn',N'Nguyễn Duy Minh Tuệ',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('trinhvlb@fe.edu.vn',N'Vũ Lê Bảo Trinh',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('nhi.htm@fe.edu.vn',N'Huỳnh Thị Mộng Nhi.',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('khanhkt@fe.edu.vn',N'Kiều Trọng Khánh',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('truonglv@fe.edu.vn',N'Lê Vũ trường',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('annđh@fe.edu.vn',N'Ngô Đăng Hà An',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('sutv@fe.edu.vn',N'Thân Văn Sử',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('hoangnt@fe.edu.vn',N'Nguyễn Thế Hoàng',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('duongvtt@fe.edu.vn',N'Vũ Thị Thùy Dương',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('senb@fe.edu.vn',N'Bhaskar Sen',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('danhnt@fe.edu.vn',N'Nguyễn Tấn Danh',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('đinhmh@fe.edu.vn',N'Mai Hoàng Đỉnh',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('vanttn@fe.edu.vn',N'Thân Thị Ngọc Vân',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('kiemhh@fe.edu.vn',N'Hồ Hoàn Kiếm',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('thongnt@fe.edu.vn',N'Nguyễn Trí Thông',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('ngocttm@fe.edu.vn',N'Trương Thị Mỹ Ngọc',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('huongntc@fe.edu.vn',N'Nguyễn Thị Cẩm Hương',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('trucntt@fe.edu.vn',N'Nguyễn Thị Thanh Trúc',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('phuonglhk@fe.edu.vn',N'Lâm hữu Khánh Phương',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('vanvtt@fe.edu.vn',N'Võ Thị Thanh Vân',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('loanltb@fe.edu.vn',N'Lê Thị bích Loan',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('ngocntb@fe.edu.vn',N'Nguyễn Thụy Bích ngọc',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('chaupb@fe.edu.vn',N'Phan Bảo Châu',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('tannv@fe.edu.vn',N'Nguyễn Viết Tân',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('phuonghtc@fe.edu.vn',N'Hoàng Thị cúc Phương',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('phuongnqt@fe.edu.vn',N'Nguyễn Quốc Thụy Phương',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('tu2ltc@fe.edu.vn',N'La Thị Cẩm tú2',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('duongdt@fe.edu.vn',N'Dư Tiểu Dương',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('lan2ln@fe.edu.vn',N'Lưu Nhật Lan2',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('nhutnm@fe.edu.vn',N'Trần Ngọc Minh Như',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('quangnc@fe.edu.vn',N'Nguyễn Chính Quang',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null),
('nguyenlnp@fe.edu.vn',N'Lê Ngọc Phương Nguyên',null,'https://meet.google.com/ryu-stnz-rww',1,null,null,null,null);


